### ISSUE TITLE
A man needs a doc

### ISSUE THREAD

**Issue by Lgt2x** [mxyns/collinsa#2]
Document your code so anyone can read it. For the sake of this project, do it.
Imagine 1 puppy dies for 1 undocumented function or class

**Comment by mxyns** [comment]
Most of the code is already documented. Also, you could've known that the next commit will be about the missing javadoc, but you didn't care enough to read my commit messages. I know that yours don't contain any kind of information on the changes made to the files whatsoever but mine do, so please consider reading them before opening useless issues.

**Comment by Lgt2x** [comment]
Commit messages are definitely not the right place for this. I don't need no personal attacks, so document your code already.
Plus, I love to fill your inbox

**Comment by mxyns** [comment]
Yeah I noticed your love for my inbox. I too, am really fond of filling your inbox, that's why I'm answering these. 
Btw I don't have any devblog so commit messages will continue to contain every information you need to know.
